Completed Assignment - 2
ashok-cdw/Java-Training pull request #2
Opened 2023-03-17 05:55 UTC by ashok-cdw

2023-03-17 08:24 UTC, Adheesh-Sirius requested changes

2023-03-17 08:24 UTC, Adheesh-Sirius commented on Task - 2/AverageOfMarks.java
> +				System.out.println("Wrong Input");
Can you update the logic so that the program asks for the input again when they enter a wrong input?

2023-03-17 09:31 UTC, ashok-cdw commented on Task - 2/AverageOfMarks.java
> +				System.out.println("Wrong Input");
updated the logic

2023-03-21 09:49 UTC, Adheesh-Sirius approved these changes

2023-03-21 09:49 UTC, merged